CREATE DATABASE DESAFIODOCK;
USE DESAFIODOCK;
COMMIT;

CREATE TABLE PESSOA (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CPF VARCHAR(255) NOT NULL,
  DATA_NASCIMENTO DATETIME NOT NULL,
  NOME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (CPF)
);
COMMIT;

CREATE TABLE CONTA (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  DATA_TRANSACAO DATETIME DEFAULT NULL,
  FLAG_ATIVO BIT(1) DEFAULT NULL,
  LIMITE_SAQUE_DIARIO DECIMAL(11,2) NOT NULL,
  SALDO DECIMAL(11,2) NOT NULL,
  TIPO_CONTA INT(11) NOT NULL,
  PESSOA_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  KEY (PESSOA_ID)
);
COMMIT;

CREATE TABLE TRANSACAO (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  DATA_TRANSACAO DATE DEFAULT NULL,
  TIPO_TRANSACAO INT(11) NOT NULL,
  VALOR DECIMAL(11,2) NOT NULL,
  CONTA_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  KEY (CONTA_ID)
);
COMMIT;